export const INDUSTRY_CODES = [
    { code: '11', label: 'Agriculture, forestry, fishing, and hunting' },
    { code: '2211', label: 'Electric power generation, transmission, and distribution' },
    { code: '2212', label: 'Natural gas distribution' },
    { code: '2213', label: 'Water, sewage, and other systems' },
    { code: '23', label: 'Construction & installation' },
    { code: '311', label: 'Food manufacturing' },
    { code: '3121B', label: 'Non-alcoholic beverage manufacturing' },
    { code: '313', label: 'Textile mills' },
    { code: '314', label: 'Textile product mills' },
    { code: '315', label: 'Apparel manufacturing' },
    { code: '316', label: 'Leather and allied product manufacturing' },
    { code: '321', label: 'Wood product manufacturing' },
    { code: '322', label: 'Paper manufacturing' },
    { code: '323', label: 'Printing and related support activities' },
    { code: '3255', label: 'Paint, coating, and adhesive manufacturing' },
    { code: '326', label: 'Plastics and rubber products manufacturing' },
    { code: '327', label: 'Nonmetallic mineral product manufacturing' },
    { code: '331', label: 'Primary metal manufacturing' },
    { code: '332', label: 'Fabricated metal product manufacturing' },
    { code: '333', label: 'Machinery manufacturing' },
    { code: '334', label: 'Computer and electronic product manufacturing' },
    { code: '335', label: 'Electrical equipment, appliance, and component manufacturing' },
    { code: '336', label: 'Transportation (equipment) manufacturing' },
    { code: '337', label: 'Furniture and related product manufacturing' },
    { code: '339D', label: 'Other miscellaneous durable goods manufacturing' },
    { code: '339E', label: 'Other miscellaneous nondurable goods manufacturing' },
    { code: '4232', label: 'Furniture and home furnishing merchant wholesalers' },
    { code: '4233', label: 'Lumber and other construction materials merchant wholesalers' },
    { code: '42341', label: 'Photographic equipment and supplies merchant wholesalers' },
    { code: '42342', label: 'Office equipment merchant wholesalers' },
    { code: '42343', label: 'Computer and computer peripheral equipment and software merchant wholesalers' },
    { code: '42344', label: 'Other commercial equipment merchant wholesalers' },
    { code: '42349', label: 'Other professional equipment and supplies merchant wholesalers' },
    { code: '4235', label: 'Metal and mineral (except petroleum) merchant wholesalers' },
    { code: '4236', label: 'Household appliances, electrical, and electronic goods merchant wholesalers' },
    { code: '4237', label: 'Hardware, plumbing, and heating equipment and supplies merchant wholesalers' },
    { code: '4238', label: 'Machinery, equipment, and supplies merchant wholesalers' },
    { code: '42399', label: 'Other miscellaneous durable goods merchant wholesalers' },
    { code: '4241', label: 'Paper and paper products merchant wholesalers' },
    { code: '4243', label: 'Apparel, piece goods, and notions merchant wholesalers' },
    { code: '4244', label: 'Grocery and related products merchant wholesalers' },
    { code: '4245', label: 'Farm product raw material merchant wholesalers' },
    { code: '42491', label: 'Farm supplies merchant wholesalers' },
    { code: '42492', label: 'Book, periodical, and newspaper merchant wholesalers' },
    { code: '42493', label: 'Flower, nursery stock, and florists\' supplies merchant wholesalers' },
    { code: '42495', label: 'Paint, varnish, and supplies merchant wholesalers' },
    { code: '42499', label: 'Other miscellaneous nondurable goods merchant wholesalers' },
    { code: '42511', label: 'Business-to-business electronic markets' },
    { code: '42512', label: 'Wholesale trade agents and brokers' },
    { code: '44121', label: 'Recreational vehicle dealers' },
    { code: '4412A', label: 'Mobile home dealers' },
    { code: '4412B', label: 'Utility trailer dealers' },
    { code: '441222', label: 'Boat dealers' },
    { code: '441228', label: 'Motorcycle, ATV, and all other motor vehicle dealers' },
    { code: '442A', label: 'Furniture stores' },
    { code: '442B', label: 'Home furnishings stores' },
    { code: '443141', label: 'Household appliance stores' },
    { code: '443142', label: 'Electronics stores' },
    { code: '4431A', label: 'Computer software stores' },
    { code: '4431B', label: 'Telecommunication Equipment and Telephone Stores' },
    { code: '44411', label: 'Home centers' },
    { code: '44412', label: 'Paint and wallpaper stores' },
    { code: '44413', label: 'Hardware stores' },
    { code: '44419', label: 'Other building material stores' },
    { code: '4451', label: 'Grocery stores, Supermarkets' },
    { code: '4452', label: 'Specialty food stores' },
    { code: '311811', label: 'Bakeries' },
    { code: '44612', label: 'Cosmetics, beauty supplies, and perfume stores' },
    { code: '44613', label: 'Optical goods store' },
    { code: '446199', label: 'All other health and personal care stores' },
    { code: '447', label: 'Gasoline stations' },
    { code: '44811', label: 'Men\'s clothing stores' },
    { code: '44812', label: 'Women\'s clothing stores' },
    { code: '4481A', label: 'Men\'s and Women\'s clothing stores' },
    { code: '44813', label: 'Children\'s and Infants\' clothing stores' },
    { code: '44814', label: 'Family clothing stores' },
    { code: '4481B', label: 'Sports and riding apparel stores' },
    { code: '44819', label: 'Other Clothing (accessories) stores' },
    { code: '4482', label: 'Shoe stores' },
    { code: '44832', label: 'Luggage and leather goods stores' },
    { code: '45111', label: 'Sporting goods stores' },
    { code: '45112', label: 'Hobby, toy, and game stores' },
    { code: '45113', label: 'Sewing, needlework, and piece Goods stores' },
    { code: '45114', label: 'Musical instrument and supplies stores' },
    { code: '4512', label: 'Book stores and news dealers' },
    { code: '4522', label: 'Department stores' },
    { code: '4523', label: 'General merchandise stores, including warehouse clubs and supercenters' },
    { code: '4531', label: 'Florists' },
    { code: '45321', label: 'Office supplies and stationery stores' },
    { code: '45322', label: 'Gift, novelty, and souvenir stores' },
    { code: '4533', label: 'Used merchandise stores' },
    { code: '45391', label: 'Pet and Pet Supplies stores' },
    { code: '45393', label: 'Manufactured (mobile) home dealers' },
    { code: '4539H', label: 'Discount stores' },
    { code: '4539I', label: 'Duty-free stores' },
    { code: '4539J', label: 'Second hand stores' },
    { code: '4539K', label: 'Antique stores' },
    { code: '453998', label: 'All other miscellaneous store retailers' },
    { code: '4542A', label: 'Vending machines (Food)' },
    { code: '4542B', label: 'Vending machines (Non-Food)' },
    { code: '481B', label: 'Other air transportation' },
    { code: '482A', label: 'Passenger rail transportation' },
    { code: '482B', label: 'Freight rail transportation' },
    { code: '483B', label: 'Ferries' },
    { code: '483C', label: 'Water Freight' },
    { code: '484', label: 'Truck transportation' },
    { code: '4851', label: 'Urban transit systems' },
    { code: '4852', label: 'Interurban and rural bus transportation' },
    { code: '4853', label: 'Taxi and limousine service' },
    { code: '4854', label: 'School and employee bus transportation' },
    { code: '4855', label: 'Charter bus industry' },
    { code: '4859', label: 'Other transit and ground passenger transportation' },
    { code: '4881A', label: 'Airports, airport terminals, flying fields' },
    { code: '48819', label: 'Other support activities for air transportation' },
    { code: '4882', label: 'Support activities for rail transportation' },
    { code: '4883', label: 'Support Activities for water Transportation' },
    { code: '48841', label: 'Motor vehicle towing' },
    { code: '4884A', label: 'Bridge and road fees, tolls' },
    { code: '4884B', label: 'Electric vehicle charging' },
    { code: '48849', label: 'Other support activities for road transportation' },
    { code: '4889', label: 'Other support activities for transportation' },
    { code: '491', label: 'Postal service' },
    { code: '492', label: 'Couriers and messengers' },
    { code: '493', label: 'Warehousing and storage' },
    { code: '5111', label: 'Newspaper, periodical, book, and directory publishers (except internet)' },
    { code: '5112A', label: 'Digital goods - audiovisual media including books, movies, and music' },
    { code: '5112B', label: 'Digital goods - games' },
    { code: '51121', label: 'Digital goods - software applications' },
    { code: '51211', label: 'Motion picture and video production' },
    { code: '51212', label: 'Motion picture and video distribution' },
    { code: '51213', label: 'Motion picture and video exhibition' },
    { code: '5122', label: 'Sound recording industries' },
    { code: '515', label: 'Broadcasting (except internet)' },
    { code: '517311', label: 'Wired and Wireless Telecommunications Carriers' },
    { code: '51731B', label: 'Wireless telecommunications carriers - Prepaid' },
    { code: '51731D', label: 'Other wireless telecommunications carriers' },
    { code: '5179', label: 'Other telecommunications' },
    { code: '517911', label: 'Telecommunications Resellers' },
    { code: '51911', label: 'News Agency' },
    { code: '51913', label: 'Internet publishing and broadcasting and web search portals' },
    { code: '5191A', label: 'All other information services' },
    { code: '53211', label: 'Passenger car rental and leasing' },
    { code: '53212', label: 'Truck, and utility trailer rental and leasing' },
    { code: '5321B', label: 'Motor home and recreational vehicle rental' },
    { code: '53221', label: 'Consumer electronics and appliances rental' },
    { code: '532281', label: 'Formal wear and costume rental' },
    { code: '532282', label: 'Video tape and disc rental' },
    { code: '532283', label: 'Home health equipment rental' },
    { code: '532284', label: 'Recreational goods rental' },
    { code: '532289', label: 'All other consumer goods rental' },
    { code: '5324', label: 'Commercial, industrial machinery and equipment rental and leasing' },
    { code: '5411A', label: 'Lawyers (except bankruptcy)' },
    { code: '541211', label: 'Offices of certified public accountants' },
    { code: '541213', label: 'Tax preparation services' },
    { code: '5413', label: 'Architectural, engineering, and related services' },
    { code: '5414', label: 'Specialized design services' },
    { code: '5415', label: 'Computer systems design and related services' },
    { code: '5416', label: 'Management, scientific, and technical consulting services' },
    { code: '54171', label: 'Research and development in the Physical, Engineering, and Life Sciences' },
    { code: '5417B', label: 'Other research and development in the Social Sciences and Humanities' },
    { code: '5418', label: 'Advertising, public relations, and related services' },
    { code: '54192', label: 'Photographic services' },
    { code: '54194', label: 'Veterinary services' },
    { code: '54199', label: 'All other professional, scientific, and technical services' },
    { code: '55', label: 'Management of companies and enterprises' },
    { code: '5611', label: 'Office administrative services' },
    { code: '5612', label: 'Facilities support services' },
    { code: '5613', label: 'Employment services' },
    { code: '56141', label: 'Document preparation services' },
    { code: '56142', label: 'Telephone call centers' },
    { code: '56143', label: 'Business service centers' },
    { code: '56149', label: 'Other business support services' },
    { code: '5616A', label: 'Security services' },
    { code: '56171', label: 'Exterminating and pest control services' },
    { code: '56172', label: 'Janitorial services' },
    { code: '56173', label: 'Landscaping services' },
    { code: '56174', label: 'Carpet and upholstery cleaning services' },
    { code: '56179', label: 'Other services to buildings and dwellings' },
    { code: '5619', label: 'Other support services' },
    { code: '562', label: 'Waste management and remediation services' },
    { code: '6111', label: 'Elementary and secondary schools' },
    { code: '6112', label: 'Junior colleges' },
    { code: '6113', label: 'Colleges, universities, and professional schools' },
    { code: '6114', label: 'Business schools, and computer and management training' },
    { code: '6115', label: 'Technical and trade schools' },
    { code: '6116A', label: 'Dance Schools' },
    { code: '61161', label: 'Fine arts schools' },
    { code: '61162', label: 'Sports and recreation instruction' },
    { code: '61163', label: 'Language schools' },
    { code: '61169', label: 'All other schools and instruction' },
    { code: '6214', label: 'Outpatient care centers' },
    { code: '6219', label: 'Other ambulatory health care services' },
    { code: '6241', label: 'Individual and family services' },
    { code: '6242', label: 'Community food and housing, and emergency and other relief services' },
    { code: '6243', label: 'Vocational rehabilitation services' },
    { code: '6244', label: 'Child day care services' },
    { code: '624A', label: 'All other social services' },
    { code: '7111', label: 'Performing arts companies' },
    { code: '7112', label: 'Spectator sports' },
    { code: '7113', label: 'Promoters of performing arts, sports, and similar events' },
    { code: '7114', label: 'Agents and managers for artists, athletes, entertainers, and other public figures' },
    { code: '7115', label: 'Independent artists, writers, and performers' },
    { code: '712', label: 'Museums, historical sites, and similar institutions' },
    { code: '71311', label: 'Amusement and theme parks' },
    { code: '71312', label: 'Amusement arcades' },
    { code: '7139A', label: 'Public golf courses' },
    { code: '7139B', label: 'Private golf courses and country clubs' },
    { code: '71392', label: 'Skiing facilities' },
    { code: '71393', label: 'Marinas' },
    { code: '71394', label: 'Fitness and recreational sports centers' },
    { code: '71395', label: 'Bowling centers' },
    { code: '7139C', label: 'All other amusement and recreation industries' },
    { code: '7139D', label: 'Billiard and pool establishments' },
    { code: '7139E', label: 'Aquariums, seaquariums, dolphinariums, and zoos' },
    { code: '72111', label: 'Hotels (except casino hotels) and motels' },
    { code: '7211B', label: 'Other traveler accommodation' },
    { code: '7212', label: 'Recreational vehicle parks and recreational camps' },
    { code: '7213', label: 'Rooming and boarding houses, dormitories, and workers\' Camps' },
    { code: '7223', label: 'Special food services' },
    { code: '722511', label: 'Full-service restaurants' },
    { code: '722513', label: 'Limited-service restaurants (Fast food restaurants)' },
    { code: '722514', label: 'Cafeterias, grill buffets, and buffets' },
    { code: '722515', label: 'Snacks and nonalcoholic beverage bars' },
    { code: '8111', label: 'Automotive repair and maintenance' },
    { code: '8112', label: 'Electronic and precision equipment repair and maintenance (including computers)' },
    { code: '8113', label: 'Commercial and industrial machinery and equipment (except automotive and electronic) repair and maintenance' },
    { code: '8114', label: 'Personal and household goods repair and maintenance' },
    { code: '81211', label: 'Hair, nail, and skin care services' },
    { code: '8121A', label: 'Massage parlors' },
    { code: '8121B', label: 'Health and beauty spas' },
    { code: '8122', label: 'Death care services' },
    { code: '8123', label: 'Drycleaning and Laundry services' },
    { code: '8129E', label: 'Other personal services' },
    { code: '8134', label: 'Civic and social organizations' },
    { code: '81391', label: 'Business associations' },
    { code: '81392', label: 'Professional organizations' },
    { code: '81393', label: 'Labor unions and similar labor organizations' },
    { code: '81399', label: 'Other similar organizations (except business, professional, labor, and political organizations)' },
];

export const MCC_CODES = [
    { code: '3000', label: 'Airlines - United Airlines' },
    { code: '3010', label: 'Airlines - KLM' },
    { code: '3389', label: 'Airlines - Aer Lingus' },
    { code: '3504', label: 'Car Rental - Hertz' },
    { code: '5411', label: 'Grocery Stores, Supermarkets' },
    { code: '5412', label: 'Convenience Stores' },
    { code: '5499', label: 'Miscellaneous Food Stores' },
    { code: '5541', label: 'Service Stations (Gas Stations)' },
    { code: '5542', label: 'Automated Fuel Dispensers' },
    { code: '5812', label: 'Restaurants' },
    { code: '5813', label: 'Bars, Cocktail Lounges, Nightclubs', risky: true },
    { code: '5814', label: 'Fast Food Restaurants' },
    { code: '5912', label: 'Drug Stores, Pharmacies' },
    { code: '5311', label: 'Department Stores' },
    { code: '5331', label: 'Variety Stores' },
    { code: '5651', label: 'Family Clothing Stores' },
    { code: '5691', label: 'Men\'s & Women\'s Clothing Stores' },
    { code: '5732', label: 'Electronics Stores' },
    { code: '5733', label: 'Music Stores' },
    { code: '5734', label: 'Computer Software Stores' },
    { code: '5735', label: 'Record Shops' },
    { code: '5941', label: 'Sporting Goods Stores' },
    { code: '5942', label: 'Book Stores' },
    { code: '5944', label: 'Jewelry Stores' },
    { code: '5945', label: 'Hobby, Toy & Game Shops' },
    { code: '5947', label: 'Gift, Card, Novelty Shops' },
    { code: '7011', label: 'Hotels, Motels, Resorts' },
    { code: '7230', label: 'Beauty and Barber Shops', risky: true },
    { code: '7297', label: 'Massage Parlors, Health and Beauty Spas', risky: true },
    { code: '7832', label: 'Movie Theaters' },
    { code: '7841', label: 'Video Tape Rental Stores' },
    { code: '7922', label: 'Theatrical Producers' },
    { code: '7929', label: 'Bands, Orchestras, Entertainment' },
    { code: '7991', label: 'Tourist Attractions' },
    { code: '7993', label: 'Video Game Arcades' },
    { code: '7994', label: 'Video Game Arcades/Establishments' },
    { code: '7995', label: 'Gambling - Betting, Casinos, Lottery' },
    { code: '7996', label: 'Amusement Parks, Carnivals' },
    { code: '7997', label: 'Country Clubs, Membership Clubs' },
    { code: '7998', label: 'Aquariums, Dolphinariums, Zoos' },
    { code: '7999', label: 'Recreation Services' },
    { code: '4111', label: 'Local/Suburban Transportation' },
    { code: '4112', label: 'Passenger Railways' },
    { code: '4121', label: 'Taxicabs & Limousines' },
    { code: '4131', label: 'Bus Lines' },
    { code: '4411', label: 'Cruise Lines' },
    { code: '4511', label: 'Airlines' },
    { code: '4722', label: 'Travel Agencies' },
    { code: '4784', label: 'Toll & Bridge Fees' },
    { code: '4789', label: 'Transportation Services' },
    { code: '5962', label: 'Direct Marketing - Travel' },
    { code: '5963', label: 'Door-to-Door Sales' },
    { code: '5964', label: 'Direct Marketing - Catalog' },
    { code: '5965', label: 'Direct Marketing - Catalog/Retail' },
    { code: '5966', label: 'Direct Marketing - Outbound Telemarketing' },
    { code: '5967', label: 'Direct Marketing - Inbound Telemarketing' },
    { code: '5968', label: 'Direct Marketing - Subscription' },
    { code: '5969', label: 'Direct Marketing - Other' },
    { code: '6010', label: 'Financial Institutions - Cash Disbursements' },
    { code: '6011', label: 'ATM Cash Withdrawals' },
    { code: '6012', label: 'Financial Institutions - Merchandise' },
    { code: '6051', label: 'Non-Financial Institutions - Foreign Currency, Money Orders' },
    { code: '6211', label: 'Security Brokers/Dealers' },
    { code: '6300', label: 'Insurance Sales & Services' },
    { code: '6513', label: 'Real Estate Agents - Rentals' },
    { code: '9222', label: 'Fines' },
    { code: '9311', label: 'Tax Payments' },
    { code: '9399', label: 'Government Services' }
];

