export const INDUSTRY_CODES = [
    { code: '23', label: 'Construction & installation' },
    { code: '311', label: 'Food manufacturing' },
    { code: '4451', label: 'Grocery stores, Supermarkets' },
    { code: '722511', label: 'Full-service restaurants' },
    { code: '722513', label: 'Limited-service restaurants (Fast food)' },
    { code: '8111', label: 'Automotive repair and maintenance' },
    { code: '81211', label: 'Hair, nail, and skin care services' },
    { code: '541211', label: 'Offices of certified public accountants' },
    { code: '541213', label: 'Tax preparation services' },
    { code: '5413', label: 'Architectural, engineering, and related services' },
    { code: '5415', label: 'Computer systems design and related services' },
    { code: '5416', label: 'Management, scientific, and technical consulting services' },
    { code: '4238', label: 'Machinery, equipment, and supplies merchant wholesalers' },
    { code: '4244', label: 'Grocery and related products merchant wholesalers' },
    { code: '44811', label: "Men's clothing stores" },
    { code: '44812', label: "Women's clothing stores" },
    { code: '44814', label: 'Family clothing stores' },
    { code: '443142', label: 'Electronics stores' },
    { code: '442A', label: 'Furniture stores' },
    { code: '493', label: 'Warehousing and storage' },
    { code: '484', label: 'Truck transportation' },
    { code: '72111', label: 'Hotels (except casino hotels) and motels' },
    { code: '6244', label: 'Child day care services' },
    { code: '711A', label: 'Ticketing agencies' }
];

export const MCC_CODES = [
    { code: '3000', label: 'Airlines - United Airlines' },
    { code: '3010', label: 'Airlines - KLM' },
    { code: '3389', label: 'Airlines - Aer Lingus' },
    { code: '3504', label: 'Car Rental - Hertz' },
    { code: '5411', label: 'Grocery Stores, Supermarkets' },
    { code: '5412', label: 'Convenience Stores' },
    { code: '5499', label: 'Miscellaneous Food Stores' },
    { code: '5541', label: 'Service Stations (Gas Stations)' },
    { code: '5542', label: 'Automated Fuel Dispensers' },
    { code: '5812', label: 'Restaurants' },
    { code: '5813', label: 'Bars, Cocktail Lounges, Nightclubs', risky: true },
    { code: '5814', label: 'Fast Food Restaurants' },
    { code: '5912', label: 'Drug Stores, Pharmacies' },
    { code: '5311', label: 'Department Stores' },
    { code: '5331', label: 'Variety Stores' },
    { code: '5651', label: 'Family Clothing Stores' },
    { code: '5691', label: 'Men\'s & Women\'s Clothing Stores' },
    { code: '5732', label: 'Electronics Stores' },
    { code: '5733', label: 'Music Stores' },
    { code: '5734', label: 'Computer Software Stores' },
    { code: '5735', label: 'Record Shops' },
    { code: '5941', label: 'Sporting Goods Stores' },
    { code: '5942', label: 'Book Stores' },
    { code: '5944', label: 'Jewelry Stores' },
    { code: '5945', label: 'Hobby, Toy & Game Shops' },
    { code: '5947', label: 'Gift, Card, Novelty Shops' },
    { code: '7011', label: 'Hotels, Motels, Resorts' },
    { code: '7230', label: 'Beauty and Barber Shops', risky: true },
    { code: '7297', label: 'Massage Parlors, Health and Beauty Spas', risky: true },
    { code: '7832', label: 'Movie Theaters' },
    { code: '7841', label: 'Video Tape Rental Stores' },
    { code: '7922', label: 'Theatrical Producers' },
    { code: '7929', label: 'Bands, Orchestras, Entertainment' },
    { code: '7991', label: 'Tourist Attractions' },
    { code: '7993', label: 'Video Game Arcades' },
    { code: '7994', label: 'Video Game Arcades/Establishments' },
    { code: '7995', label: 'Gambling - Betting, Casinos, Lottery' },
    { code: '7996', label: 'Amusement Parks, Carnivals' },
    { code: '7997', label: 'Country Clubs, Membership Clubs' },
    { code: '7998', label: 'Aquariums, Dolphinariums, Zoos' },
    { code: '7999', label: 'Recreation Services' },
    { code: '4111', label: 'Local/Suburban Transportation' },
    { code: '4112', label: 'Passenger Railways' },
    { code: '4121', label: 'Taxicabs & Limousines' },
    { code: '4131', label: 'Bus Lines' },
    { code: '4411', label: 'Cruise Lines' },
    { code: '4511', label: 'Airlines' },
    { code: '4722', label: 'Travel Agencies' },
    { code: '4784', label: 'Toll & Bridge Fees' },
    { code: '4789', label: 'Transportation Services' },
    { code: '5962', label: 'Direct Marketing - Travel' },
    { code: '5963', label: 'Door-to-Door Sales' },
    { code: '5964', label: 'Direct Marketing - Catalog' },
    { code: '5965', label: 'Direct Marketing - Catalog/Retail' },
    { code: '5966', label: 'Direct Marketing - Outbound Telemarketing' },
    { code: '5967', label: 'Direct Marketing - Inbound Telemarketing' },
    { code: '5968', label: 'Direct Marketing - Subscription' },
    { code: '5969', label: 'Direct Marketing - Other' },
    { code: '6010', label: 'Financial Institutions - Cash Disbursements' },
    { code: '6011', label: 'ATM Cash Withdrawals' },
    { code: '6012', label: 'Financial Institutions - Merchandise' },
    { code: '6051', label: 'Non-Financial Institutions - Foreign Currency, Money Orders' },
    { code: '6211', label: 'Security Brokers/Dealers' },
    { code: '6300', label: 'Insurance Sales & Services' },
    { code: '6513', label: 'Real Estate Agents - Rentals' },
    { code: '9222', label: 'Fines' },
    { code: '9311', label: 'Tax Payments' },
    { code: '9399', label: 'Government Services' }
];

