app.frontend.url=http://localhost:4200
app.backend.url=http://localhost:8080

spring.datasource.url=jdbc:sqlite:users.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
adyen.balancePlatformApiKey=
adyen.lemApiKey=
adyen.pspApiKey=
adyen.merchantAccount=
adyen.clientKey=
adyen.lemVersion=v4
adyen.issuing.country=
adyen.issuing.visa.subvariant=
adyen.issuing.mastercard.subvariant=
